-- =====================================================================
-- Money & quantity precision: Float (double precision) -> Decimal/Numeric.
-- Widening in-place ALTERs — PostgreSQL casts existing double values to
-- numeric losslessly for the magnitudes used here. No data is dropped.
-- Precision policy: amounts Decimal(20,4), quantities Decimal(20,6),
-- percentages Decimal(9,4), exchange rate Decimal(20,10), leave days Decimal(9,2).
-- Reversible in principle, but take a backup first (see STAGED_UPGRADES.md).
-- =====================================================================

-- AlterTable
ALTER TABLE "ExchangeRate" ALTER COLUMN "rate" SET DATA TYPE DECIMAL(20,10);

-- AlterTable
ALTER TABLE "TaxCode" ALTER COLUMN "rate" SET DATA TYPE DECIMAL(20,10);

-- AlterTable
ALTER TABLE "PaymentTerm" ALTER COLUMN "earlyPaymentDiscount" SET DATA TYPE DECIMAL(9,4);

-- AlterTable
ALTER TABLE "Partner" ALTER COLUMN "creditLimit" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "openingBalance" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "currentBalance" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "costPrice" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "salePrice" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "minStock" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "maxStock" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "reorderPoint" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "StockQuant" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "reservedQty" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "StockMove" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "valuationAmount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "costPrice" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "StockValuationLayer" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "totalValue" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "remainingQty" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "StockReservation" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "balance" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "JournalEntry" ALTER COLUMN "totalDebit" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "totalCredit" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "JournalLine" ALTER COLUMN "debit" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "credit" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "BankAccount" ALTER COLUMN "balance" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "Safe" ALTER COLUMN "balance" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesQuotation" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesQuotationLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discountPercent" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesOrder" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "paid" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesOrderLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "deliveredQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "invoicedQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discountPercent" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesInvoice" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "paid" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesInvoiceLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discountPercent" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesCreditNote" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesPayment" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "PurchaseRequestLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "PurchaseOrder" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "paid" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "PurchaseOrderLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "receivedQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "invoicedQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discountPercent" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "GoodsReceiptLine" ALTER COLUMN "orderedQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "receivedQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "PurchaseInvoice" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "paid" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "PurchaseInvoiceLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discountPercent" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "PurchaseCreditNote" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "PurchasePayment" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "DeliveryLine" ALTER COLUMN "orderedQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "deliveredQty" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "StockTransferLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "doneQty" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "InventoryAdjustmentLine" ALTER COLUMN "systemQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "countedQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "variance" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "Bom" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "BomComponent" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "scrapPercent" SET DATA TYPE DECIMAL(9,4);

-- AlterTable
ALTER TABLE "WorkCenter" ALTER COLUMN "capacityPerHour" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "costPerHour" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "ProductionOrder" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "producedQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "scrapQty" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "totalCost" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "Contract" ALTER COLUMN "baseSalary" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "allowances" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "LeaveRequest" ALTER COLUMN "days" SET DATA TYPE DECIMAL(9,2);

-- AlterTable
ALTER TABLE "PayrollRun" ALTER COLUMN "totalGross" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "totalDeductions" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "totalNet" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "Payslip" ALTER COLUMN "grossSalary" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "allowances" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "deductions" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "netSalary" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesReturn" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesReturnLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "PurchaseReturn" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "PurchaseReturnLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "Revenue" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "SalesCreditNoteLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discountPercent" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

-- AlterTable
ALTER TABLE "PurchaseCreditNoteLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "discountPercent" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(20,4),
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(9,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,4);

